services:
  nginx:
    build: frontend/.
    container_name: nginx
    ports:
      - 8080:8080
    networks:
      - transcendence    

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - transcendence
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - transcendence
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx_exporter
    command: -nginx.scrape-uri http://nginx:8080/nginx_status
    ports:
      - 9113:9113
    networks:
      - transcendence

networks:
  transcendence:
    name: transcendence