services:
  frontend:
    build: frontend/.
    container_name: frontend
    ports:
      - 8080:8080
    networks:
      - transcendence
    volumes:
      - ./frontend:/app
      - /app/node_modules
    
  backend:
    build: backend/.
    container_name: backend
    ports:
      - "3001:3001"
    networks:
      - transcendence
    volumes:
      - ./backend:/app
      - /app/node_modules

  #Devops
  elasticsearch:
    image: elasticsearch:7.8.1
    ports:
      - 9200:9200
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'true'
      ELASTIC_PASSWORD: 'admin'
      ES_JAVA_OPTS: '-Xmx2g -Xms2g'
  kibana:
    image: kibana:7.8.1
    volumes:
      - ./monitoring/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    

  #--------------------#
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - transcendence
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - transcendence
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx_exporter
    command: -nginx.scrape-uri http://nginx:8080/nginx_status
    ports:
      - 9113:9113
    networks:
      - transcendence

networks:
  transcendence:
    name: transcendence
